# Course Service Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: edutrack
  labels:
    app: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      serviceAccountName: course-service-sa
      containers:
        - name: course-service
          image: gcr.io/sincere-tape-471709-e5/course-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: edutrack-config
                  key: NODE_ENV
            - name: DB_HOST
              value: "10.54.32.3"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: course-db-credentials
                  key: DB_NAME
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: edutrack
  labels:
    app: course-service
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: course-service
