# Enrollment Service Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
  namespace: edutrack
  labels:
    app: enrollment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      serviceAccountName: enrollment-service-sa
      containers:
        - name: enrollment-service
          image: gcr.io/sincere-tape-471709-e5/enrollment-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: edutrack-config
                  key: NODE_ENV
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: enrollment-db-credentials
                  key: DB_NAME
            - name: STUDENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: edutrack-config
                  key: STUDENT_SERVICE_URL
            - name: COURSE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: edutrack-config
                  key: COURSE_SERVICE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          args:
            - "/cloud_sql_proxy"
            - "-instances=sincere-tape-471709-e5:us-central1:edutrack-postgres=tcp:5432"
            - "-credential_file=/secrets/key.json"
          volumeMounts:
            - name: cloudsql-sa
              mountPath: /secrets
              readOnly: true
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
      volumes:
        - name: cloudsql-sa
          secret:
            secretName: cloudsql-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: edutrack
  labels:
    app: enrollment-service
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app: enrollment-service
