apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: edutrack
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/sincere-tape-471709-e5/edutrack-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: STUDENT_SERVICE_URL
          value: "http://student-service:3001"
        - name: COURSE_SERVICE_URL
          value: "http://course-service:3002"
        - name: ENROLLMENT_SERVICE_URL
          value: "http://enrollment-service:3003"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/students # Simple check if API is up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: edutrack
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
